const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={session:null,candidates:[],selected:null,waypoints:{origin:[0,0],destination:[1,1]}};
const colors=['#55d6be','#f0ad4e','#6aa8ff','#d17fff','#ef7180'];
function auth(){const t=$('#token').value.trim();return t?{'Authorization':`Bearer ${t}`,'Content-Type':'application/json'}:{'Content-Type':'application/json'}}
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...auth(),...(opts.headers||{})}});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);return r.status===204?null:r.json()}
function project(coords){if(!coords.length)return[];const xs=coords.map(c=>c[0]),ys=coords.map(c=>c[1]);let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);if(minX===maxX){minX-=1;maxX+=1}if(minY===maxY){minY-=1;maxY+=1}return coords.map(([x,y])=>[80+(x-minX)/(maxX-minX)*840,620-(y-minY)/(maxY-minY)*540])}
function draw(){const g=$('#routes');g.innerHTML='';const all=state.candidates.flatMap(c=>c.geometry?.type==='LineString'?c.geometry.coordinates:[]);state.candidates.forEach((c,i)=>{if(c.geometry?.type!=='LineString')return;const pts=project(c.geometry.coordinates.length?c.geometry.coordinates:all);const p=document.createElementNS('http://www.w3.org/2000/svg','polyline');p.setAttribute('points',pts.map(x=>x.join(',')).join(' '));p.setAttribute('class','route'+(state.selected===c.candidate_id?' selected':''));p.setAttribute('stroke',colors[i%colors.length]);p.dataset.id=c.candidate_id;p.addEventListener('click',()=>select(c.candidate_id));g.appendChild(p)});drawWaypoints()}
function drawWaypoints(){const g=$('#waypoints');g.innerHTML='';const vals=[state.waypoints.origin,state.waypoints.destination];project(vals).forEach((pt,i)=>{const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('cx',pt[0]);c.setAttribute('cy',pt[1]);c.setAttribute('r',10);c.setAttribute('class','waypoint');c.dataset.kind=i?'destination':'origin';c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);const move=ev=>{c.setAttribute('cx',Math.max(20,Math.min(980,ev.offsetX/$('#map').clientWidth*1000)));c.setAttribute('cy',Math.max(20,Math.min(680,ev.offsetY/$('#map').clientHeight*700))};c.onpointermove=move;c.onpointerup=()=>{c.onpointermove=null}});g.appendChild(c)})}
function select(id){state.selected=id;const c=state.candidates.find(x=>x.candidate_id===id);if(!c)return;$('#whyText').innerHTML=`<b>${c.explanation||'No explanation'}</b><br><br>Hard constraints: ${(c.rejection_reasons||[]).join(', ')||'satisfied'}<br>Score factors: <code>${JSON.stringify(c.score_breakdown||{})}</code><br>Data quality: <code>${JSON.stringify(c.data_quality||{})}</code><br>Provenance: <code>${JSON.stringify(c.provenance||{})}</code>`;renderCards();draw()}
function renderCards(){const root=$('#cards');root.innerHTML='';state.candidates.forEach((c,i)=>{const d=document.createElement('div');d.className='card'+(c.candidate_id===state.selected?' selected':'');d.innerHTML=`<div><b>ROUTE ${i+1}</b> · ${c.feasibility}</div><div class="score">${c.score==null?'—':c.score.toFixed(4)}</div><div class="metrics"><span>${c.metrics?.distance_km??'—'} km</span><span>${c.metrics?.eta_minutes??'—'} min</span><span>Energy ${c.metrics?.energy_estimate??'—'}</span><span>Comms ${c.metrics?.comms_quality??'—'}</span></div>`;d.onclick=()=>select(c.candidate_id);root.appendChild(d)});if(state.candidates.length&&!state.selected)select(state.candidates[0].candidate_id)}
async function createPlan(){try{const dep=new Date($('#depart').value||Date.now()),latest=new Date($('#latest').value||Date.now()+3600000);const context=await api('/v1/routes/context');const body={plan_id:$('#planId').value,vehicle_profile_id:$('#profileId').value,dataset_id:$('#datasetId').value,origin:{lat:+$('#olat').value,lon:+$('#olon').value},destination:{lat:+$('#dlat').value,lon:+$('#dlon').value},origin_node_id:$('#originNode').value,destination_node_id:$('#destinationNode').value,planning_window:{earliest_departure:dep.toISOString(),latest_departure:latest.toISOString()},enabled_layers:$$('[data-layer]:checked').map(x=>x.dataset.layer),security_context:context,max_alternatives:4};const s=await api('/v1/routes/sessions',{method:'POST',body:JSON.stringify(body)});state.session=s.id;const gen=await api(`/v1/routes/sessions/${s.id}/generate`,{method:'POST'});state.candidates=gen.candidates||[];state.selected=null;renderCards();draw();await loadWindows()}catch(e){$('#status').textContent=e.message}}
async function loadWindows(){if(!state.session)return;try{const x=await api(`/v1/routes/sessions/${state.session}/windows`,{method:'POST',body:JSON.stringify({interval_minutes:30})});const root=$('#windowBars');root.innerHTML='';(x.windows||[]).forEach(w=>{const b=document.createElement('span');b.className='bar'+(w.recommended?' best':'');b.style.width=`${Math.max(8,100/(x.windows.length||1)-4)}%`;b.title=`${w.departure_time} · ${w.score??'unavailable'}`;root.appendChild(b)});$('#windowStatus').textContent=`${x.windows?.length||0} intervals`}catch(e){$('#windowStatus').textContent='unavailable'}}
async function replay(){try{const id=$('#replayId').value||state.session;const x=await api(`/v1/routes/sessions/${id}/replay`);$('#replayOut').textContent=JSON.stringify(x,null,2);state.candidates=x.candidates||[];renderCards();draw()}catch(e){$('#replayOut').textContent=e.message}}
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');const mode=b.dataset.mode;$('#planner').hidden=mode!=='plan';$('#replayPane').hidden=mode!=='replay';$('#candidates').hidden=mode==='replay'?false:false});$('#create').onclick=createPlan;$('#loadReplay').onclick=replay;$$('[data-layer]').forEach(x=>x.onchange=()=>$('#status').textContent=`${x.dataset.layer.toUpperCase()} ${x.checked?'ON':'OFF'}`);drawWaypoints();
